# Generated by Django 5.1.2 on 2024-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_products_delete_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/products/"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
