# Generated by Django 4.2.16 on 2024-12-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
